### ISSUE TITLE
Voice Codecs

### ISSUE THREAD

**Issue by Chazotu** [TeaSpeak/TeaWeb#11]
Integrate the following codecs in to the web client.

Error when joining a Chanel whit this codecs: You dont Support this Codecs
from that follows you cant talk in channels whit this codecs

- Speex Smalband
- Speex Breitband
- Speex Ultra-Breitband
- CELT Mono

**Comment by WolverinDEV** [comment]
Speex is implemented within the client.
CELT will be never implemented (its outdated, and was actually the parent for opus)
