### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by vibratim** [TeaSpeak/TeaWeb#130]
## System Information  
***Browser***:  Firefox
***Operating System*** (Linux|Windows|**Mac**):  
  
## Details  
***Issue type*** (Javascript | Style | System / backend | **Other** | Unknown):
  
## Issue  
***Reason for reporting this issue***:  When try connecting to TeaSpeak Server it errors out with the message "Could not connect to remote host (Connection refused)"
  
***Detailed Description***:  TeaWeb does successfully resolve the ip adress and then errors. Even with the Local IP of the TeaSpeak Server(same network and subnet!) it gets the same error.

**Comment by WolverinDEV** [comment]
Can you lookup the developer console for more details?
This seems really strange. (https://developer.mozilla.org/en-US/docs/Tools/Browser_Console#:~:text=You%20can%20open%20the%20Browser,%2BJ%20on%20a%20Mac).)

**Comment by vibratim** [comment]
Firefox isn't able to establish a "wss" connection to my server ("wss://IPADDRESS:9987/")

**Comment by WolverinDEV** [comment]
Well usually it uses the .con-gate.work as a proxy for the SSL certificate.
But what's the exact message? Is it like connection could not be established, or a certificate missmatch error.

**Comment by vibratim** [comment]
It says:
Firefox kann keine Verbindung zu dem Server unter wss://***.con-gate.work:9987/ aufbauen. 892052ba824f61bf4528.js:1:41605
Firefox kann keine Verbindung zu dem Server unter wss://***:9987/ aufbauen. 892052ba824f61bf4528.js:1:41605
[Client        ] Could not connect to remote host! Extra data:  
Object {  }
6df716a2d534960e47aa.js:1:25468

**Comment by WolverinDEV** [comment]
Well it just looks like the target server is offline :)

**Comment by vibratim** [comment]
The Server ist up and running. TS3 application works flawlessly and all needed ports are forwarded.

**Comment by WolverinDEV** [comment]
The TeaSpeak native client uses a different protocol than the web client.
The web client uses TCP ;)

**Comment by vibratim** [comment]
Yes but all ports needed are forwarded TCP and UDP alike.

**Comment by WolverinDEV** [comment]
What TeaSpeak server version are you running?

**Comment by vibratim** [comment]
The server version used is 1.4.14 :)

**Comment by WolverinDEV** [comment]
Has web been enabled within the config.yml?

**Comment by vibratim** [comment]
Yes "teaweb" is set to "yes".

**Comment by WolverinDEV** [comment]
hmmm... Can you send me your address via mail to support@teaspeak.de to test?
I'm not seeing any reason for not beeing able to connect.

**Comment by vibratim** [comment]
Send it to you :)

**Comment by WolverinDEV** [comment]
Works flawlessly for me:
![](https://img.did.science/Screenshot_15-34-18.png)

**Comment by WolverinDEV** [comment]
BTW are you now able to connect with the web client as well?
