### ISSUE TITLE
Middle Mouse click on Favorite to connect in new tab

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaWeb#138]

**Comment by WolverinDEV** [comment]
?
That's already possible, you just have to right click it ;)
(PS: Not the top bar I mean via the control bar)

**Comment by WolverinDEV** [comment]
This will not be implemented into the web client since they should work kinda similar.

**Comment by Bluscream** [comment]
I want it with Mouse3 not right-click. Just look how it works in the Teamspeak client

**Comment by WolverinDEV** [comment]
Yes, but even this is not possible.
Windows menus do not offer any control over key presses.

**Comment by Bluscream** [comment]
I am talking about the control bar, that's why this issue is in TeaSpeak/TeaWeb

**Comment by WolverinDEV** [comment]
Ahhh any why not just right click it? :D

**Comment by Bluscream** [comment]
If you open a bunch of servers in a row the chance of missclicking and accidentally overwriting a tab increases

**Comment by WolverinDEV** [comment]
implemented in the next version ;)
