### ISSUE TITLE
Missing required wasm function -  while selecting identity

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaWeb#14]
## System Information  
***Browser***:  Chrome
***Operating System***:  Linux
  
## Details  
***Issue type*** : Javascript, Webasm
  
## Issue  
***Reason for reporting this issue***:  

****Missing required wasm function!****

I was build the TeaWeb by this setup guide: https://github.com/TeaSpeak/TeaWeb/blob/master/setup.md
But while selecting teamspeak identity file I got the error:
![tea_2018-10-10_17-40-37](https://user-images.githubusercontent.com/15149258/46744702-59593c00-ccb4-11e8-991c-cb8f61e5d513.png)

**Comment by WolverinDEV** [comment]
Yeah, had that error already.
Just reload the page.
This should not be permanent

**Comment by lexesv** [comment]
I was reload the page many times) an same error...

**Comment by lexesv** [comment]
Hmm. after clear browser cache there is no more error

**Comment by WolverinDEV** [comment]
Ahh you found the error :D
Every time when you wan to reload press `SHIFT`.
Then you reload the side without cached files :)

**Comment by lexesv** [comment]
But after reload page and selecting new file - error repeated again))

**Comment by WolverinDEV** [comment]
Should be fixed :)
