### ISSUE TITLE
Failed to setup voice bridge: failed to establish a connection. Allow reconnect: Yes

### ISSUE THREAD

**Issue by cyberlimbo** [TeaSpeak/TeaWeb#142]
## System Information  
***Browser***:  
Google Chrome and Firefox

***Operating System*** (Linux|Windows|Mac):  
Windows 10 x64
  
## Details  
***Issue type*** (Javascript | Style | System / backend | Other | Unknown): 
Unknown
  
## Issue  
***Reason for reporting this issue***:  
"Failed to setup voice bridge: failed to establish a connection. Allow reconnect: Yes" message.
  
***Detailed Description***:  
This problem is happening since "Travis autobuild a02ebb0".
In "Travis autobuild 9189fc2" (and previous versions) with stun activated in the teaspeak server config
the problem is not present.
  
***Steps to reproduce***:  
TeaSpeak Server installed in a server with NAT.
When trying to connect using teaspeak webclient the microfone does not work and
this message appears.

**Comment by WolverinDEV** [comment]
Had you enabled upnp support within the config.yml?
As well TCP ports are free right?

**Comment by cyberlimbo** [comment]
Had you enabled upnp support within the config.yml?
yes, i tested with that option enable, not working.

As well TCP ports are free right?
sure.

The problem it is just present since "Travis autobuild a02ebb0" and after..

**Comment by Neuxz** [comment]
Hi, 
this issue also occurs with an Docker setup.

**Image | teaspeak/server:latest-debian**
Port configuration:
```
0.0.0.0:10101 → 10101/tcp
0.0.0.0:30303 → 30303/tcp
0.0.0.0:9987 → 9987/tcp
0.0.0.0:9987 → 9987/udp
```


**Image | teaspeak/web:latest**
Port configuration:
```
0.0.0.0:443 → 443/tcp
0.0.0.0:80 → 80/tcp
```

**Comment by cyberlimbo** [comment]
"Failed to setup voice bridge: failed to received a WebRTC answer (timeout). Allow reconnect: Yes"
This problem still continues and now it is worst cause all TeaWebClient versions 
are not working with teaspeak server v1.5.0 (NAT + Stun).

1. Only TeaWebClient version: 3981144 (and older ones) it works with NAT using stun in teaspeak servers with up to v1.4.22
2. After TeaWebClient version: 3981144 it is not working in any NAT servers (not even using stun)
3. All TeaWebClient versions are not working with teaspeak v1.5.0 nightly (NAT + stun)
:(

**Comment by WolverinDEV** [comment]
Hey,
Only the development version (web.teaspeak.dev) is kompatibel with 1.5.0. The normal web client isn't.

Interesting would be if the 1.5.0 version works with the dev version :)

**Comment by cyberlimbo** [comment]
Tested the web.teaspeak.dev with TeaSpeak server v1.5.0 nightly (not working).

**Comment by WolverinDEV** [comment]
Ahh okey that explains it.
Currently the "upnp" setting which is required for working with NAT servers isn't editable/has no effect.

This will be ofc added back soonly with the next nightlys.

**Comment by cyberlimbo** [comment]
ok.
when it is added i'll test it again ;)

**Comment by WolverinDEV** [comment]
Working on it right now.
I'll release a nightly in a few min (30 or so)

**Comment by WolverinDEV** [comment]
Nightly 2 should not respect the ice settings (building right now, will be finished in 5 min)

**Comment by WolverinDEV** [comment]
Build is now (nightly-3)

**Comment by cyberlimbo** [comment]
nightly-3 tested and not fixed.
"Failed to setup voice bridge: failed to received a WebRTC answer (timeout). Allow reconnect: Yes"

stun = 1
upnp = 1

**Comment by WolverinDEV** [comment]
Perfectly so NATed networks work again?
As well I think your other issue means something else then ;)

**Comment by WolverinDEV** [comment]
PS: Love your participation with testing.

**Comment by cyberlimbo** [comment]
> Perfectly so NATed networks work again?
> As well I think your other issue means something else then ;)

At least this erros do not occurs, but voice / sound do not work xD
Basically muted since i connect the server.
