### ISSUE TITLE
WebClient "auto-muted" after a moment

### ISSUE THREAD

**Issue by cyberlimbo** [TeaSpeak/TeaWeb#147]
## System Information  
***Browser***:  chrome
***Operating System*** (Linux|Windows|Mac):  Windows
  
***Detailed Description***:  Using TeaSpeak Server 1.5.0-nightly-3 and web.teaspeak.dev web client.
One moment after connectig the NAT server, the sound / microfone is automatically muted.
  
***Steps to reproduce***:  Go to web.teaspeak.dev and connect a teaspeak server v1.5.0-nightly-3 (using NAT newtwork).
Sound / microfone will be automatically muted after a moment.

Some extra info:
*Sometimes de message "flood ban" appears, but even after givind flood ban permissions,
the sound / microfone is being automatically muted.

**Comment by WolverinDEV** [comment]
I think it's related with the issue posted under TeaSpeak.
If the rtc bridge hasn't been set up, the clients voice is disabled.

A detailed state of your connection status can be found on the bottom.
![https://img.did.science/Screenshot_11-01-34.png](https://img.did.science/Screenshot_11-01-34.png)

**Comment by cyberlimbo** [comment]
" If the rtc bridge hasn't been set up, the clients voice is disabled. "
But it is set up xD
We can speak the first 30 seconds, after that it will "auto-mute".

**Comment by WolverinDEV** [comment]
What does "auto-mute" mean?
Headset & Microphone disabled or just not able to speak? :D

**Comment by cyberlimbo** [comment]
"A detailed state of your connection status can be found on the bottom."
Nope.  nothing is showing..

"What does "auto-mute" mean?
Headset & Microphone disabled or just not able to speak?"
Headset & Microphone disabled ;)

**Comment by WolverinDEV** [comment]
> Nope. nothing is showing..

https://travis-ci.org/github/TeaSpeak/TeaWeb

> Headset & Microphone disabled ;)

Seems like the status changes.
Just wait 'till the build has finished.
I'm curios if the web client thinks that the voice bridges drops for some reason of if its an issue somewhere else.

**Comment by cyberlimbo** [comment]
**Correction:  "We can speak the first 30 seconds"  
it is just the blue light turning on.. we cant listen the client xD

**Comment by WolverinDEV** [comment]
Ahh yeahr that's an issues if've already encountered.
Voice seems to be broken between Firefox and Chrome.

**Comment by cyberlimbo** [comment]
okok, i'll wait and test after that ;)

**Comment by cyberlimbo** [comment]
> Ahh yeahr that's an issues if've already encountered.
> Voice seems to be broken between Firefox and Chrome.

yeah, i've tested with chrome..

**Comment by cyberlimbo** [comment]
Latest dev test
"Failed to establish a voice connection:
peer connection failed"

**Comment by WolverinDEV** [comment]
Fixed with the build noted above

**Comment by cyberlimbo** [comment]
any problem?

https://travis-ci.org/github/TeaSpeak/TeaWeb

**Comment by WolverinDEV** [comment]
its out now
