### ISSUE TITLE
web.teaspeak.dev favorites duplication problem

### ISSUE THREAD

**Issue by cyberlimbo** [TeaSpeak/TeaWeb#148]
## System Information  
***Browser***:  chrome
***Operating System*** (Linux|Windows|Mac):  windows

## Issue  
***Reason for reporting this issue***:  web.teaspeak.dev client with duplication problem.
  
***Detailed Description***:  Create one server in favorites, then duplicate it and edit with different ips.. the ips will be the same in both servers.

**Comment by WolverinDEV** [comment]
Seems like bookmark editing is "broken"?.

**Comment by cyberlimbo** [comment]
yeah, something like..

**Comment by WolverinDEV** [comment]
Fixed with the build noted above.

**Comment by cyberlimbo** [comment]
![image](https://user-images.githubusercontent.com/48882447/99409554-6a3ff700-28e9-11eb-9b39-dab11f4f3653.png)
![image](https://user-images.githubusercontent.com/48882447/99409685-893e8900-28e9-11eb-9da2-eca53a459e74.png)

Tested with new web.teaspeak.dev..

**Comment by WolverinDEV** [comment]
wrong issue :D
The command execution resulted in timeout is interesting.

Is UDP and TCP enabled as well allowed by firewall?

**Comment by cyberlimbo** [comment]
"Is UDP and TCP enabled as well allowed by firewall?"
yes.
This problem only occurs with NAT servers.
Servers not using NAT do not have any problems ;)
