### ISSUE TITLE
Use browser name instead of useragent-string if possible

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaWeb#25]
Use something like https://github.com/faisalman/ua-parser-js to get a shorter version string if possible. The UA string looks like shit
```
TeaWeb 15ab95c (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36)
```

This would also allow to set the platform to the actual platform (windows,linux) etc... to not brake styles with platform icon

**Comment by Bluscream** [comment]
i think of
Version: TeaWeb %commit/version% (%browser% %version%)
Platform: %platform(Windows,Ubuntu,PlayStation,etc)%

**Comment by Bluscream** [comment]
```
Version: TeaWeb on Opera Linux x86_64
Version: TeaWeb on Chrome Win32
```
Still looks like shit and would force me to create hundrets of files also win32 is not even correct.

**Comment by WolverinDEV** [comment]
What do You mean with files?

**Comment by Bluscream** [comment]
![image](https://user-images.githubusercontent.com/3318223/50659114-d5a1a980-0f9b-11e9-878a-3905cfd2dbcd.png)

I mean that
