### ISSUE TITLE
Allow server to ask for monero donations

### ISSUE THREAD

**Issue by Bluscream** [TeaSpeak/TeaWeb#26]
It would be somewhat okay if the virtualserver had a `COINHIVE_SITE_KEY` that then the client would load the coinhive UI and ask for user consent. and the server could see the clientproperty `client_money_mined` or so and can give donation ranks accordingly. Just an idea

**Comment by Bluscream** [comment]
You could use any other service aswell. They just offer a good user-interface with selection of CPU power and threads and a user consent dialog.

**Comment by WolverinDEV** [comment]
I think this function is pritty limited and not general usable, specially because Teaspeak has nothing to do with a donation system etc. Therefore are query bots
