### ISSUE TITLE
Add a button to share the server on social networks

### ISSUE THREAD

**Issue by Vafin84** [TeaSpeak/TeaWeb#42]
I suggest to add a button to share the server on social networks. Since I'm from Russia please be sure to add social network VK.COM

**Comment by WolverinDEV** [comment]
How would you image the generated url should look like?
We've already the invite buddy dialog where multiple URL generators are available:
![](https://img.did.science/Screenshot_14-29-40.png)

I could easily add a vk.com generator there as well.

**Comment by WolverinDEV** [comment]
We now have a new share/invite system:
![image](https://user-images.githubusercontent.com/11856882/111080100-222e8b00-84fd-11eb-9eb6-f0213105b4f2.png)
