### ISSUE TITLE
uBlock Origin blocks voice communication

### ISSUE THREAD

**Issue by Sporesirius** [TeaSpeak/TeaWeb#5]
## System Information  
***Browser***:
Google Chrome

***Operating System*** (Linux|Windows|Mac): 
Windows 10
  
## Details  
***Issue type***:
- [ ] Javascript
- [ ] Style
- [ ] System / backend
- [ ] Unknown
- [x] Addon
  
## Issue  
***Reason for reporting this issue***:
I can not talk over the Web client if the uBlock Origin Addon is enabled.
  
***Detailed Description***:
The client lamp lights up, but nobody can hear me.

***Addon***:
Chrome Addon: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=de
  
***Steps to reproduce***:  
Install and Activate uBlock Origin.
  
  
  
*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by WolverinDEV** [comment]
Not a thing any more ;)
We've also an automated echo test right now
