### ISSUE TITLE
Missing sounds: Disconnect through crash + Usercrash

### ISSUE THREAD

**Issue by Nieme** [TeaSpeak/TeaWeb#59]
Sounds missing:
- [X] If someone disconnect through a crash or timeout etc., there is no sound coming.
      Example: <10:00:00> "User" timed out ( (Packet resend failed))

- [x] If the Client crashes or get timeout, I dont hear anything and dont realize that the client crashed until I saw it.

**Comment by WolverinDEV** [comment]
Fixed, the client now makes a noise and highlights the window.

Focusing the window will not be implemented, because this could be really annoying while being in game.
