### ISSUE TITLE
When initial connection to any teaspeak server, certificate error occurs.

### ISSUE THREAD

**Issue by 007basaran** [TeaSpeak/TeaWeb#72]
## System Information  
***Opera Latest***:  
***Windows*** (Linux|Windows|Mac):  
  
## Details  
***System*** (Javascript | Style | System / backend | Other | Unknown):
  
## Issue  
***YOK***:  
  
*** When initial connection to any teaspeak server, certificate error occurs. ***:  
  
***Go http://web.teaspeak.de and connect any teaspeak ip address, get certificate error.***:  
  
*Delete me: If you don't follow this issue template, you may not get a response or the issue get instantly closed.*

**Comment by WolverinDEV** [comment]
Hey,
You've to setup a certificate for your server.
A more detailed tutorial could be found here (Point 2):
https://forum.teaspeak.de/index.php?threads/setup-the-webclient-rightly-teaserver.1634/
