### ISSUE TITLE
Add URL Preview

### ISSUE THREAD

**Issue by rajmondx** [TeaSpeak/TeaWeb#76]
Previewing a url (through oembed) would be a "nice to have" feature when sending an url in any chatbox.

Includes:
- A checkbox to enable and disable previewing
- A whitelist to activate/deactivate URLs (for security purposes e.g. to avoid ip spoofing)
- A predefined default list like twitter, itunes, amazon, spotify, yolutube, github, flickr, reddit, imgure

**Comment by rajmondx** [comment]
Progress Update:

![image](https://user-images.githubusercontent.com/56911973/69500833-04e83e80-0eff-11ea-87d1-31d299a5fc15.png)

**Todos:**
- Generate `url-list` (its static for development purposes)
- Add `right` and `left` containers 
- Add modal box for `add-new-whitelisted-url`
- The `add-box` should feedback red color when its an invalid textbox
- Move the remove button at the left side 
- Add switcher (on-off) at the right side
- Figure out why the checkbox is grey when checked instead of "turquoise"
- Add a search box for URLs which tests a url too

**Comment by WolverinDEV** [comment]
You're dead? :P

**Comment by Bluscream** [comment]
Sad

**Comment by rajmondx** [comment]
Sorry gus; started a job a while ago hence no time for this *sad*
