### ISSUE TITLE
Remove GA from repo

### ISSUE THREAD

**Issue by ghost** [TeaSpeak/TeaWeb#9]
## System Information  
***Browser***:  All
***Operating System*** (Linux|Windows|Mac):  All
  
## Details  
***Issue type*** (Javascript | Style | System / backend | Other | Unknown): Javascript
  
## Issue  
***Reason for reporting this issue***:  Unnecessary Tracking
  
***Detailed Description***:  Remove the Google Analytics code from the index.php.
  
***Steps to reproduce***:  -
  
  Sorry I have no Gitclient with me otherwise I would make a pull request

**Comment by Bluscream** [comment]
The analytics are in place to improve TeaSpeak, we leave it up to the end user to block them locally.

**Comment by DieNrSieben** [comment]
Hey, 

could you explain which information of GA helps you to improve the Teaspeak web client?

I see there some data protection (Datenschutz) issues for all the users (or better systemowners)  who are deploying this repo without reading the code...

**Comment by Bluscream** [comment]
GA is GDPR compliant

**Comment by DieNrSieben** [comment]
Hey,

I didn't mean, that GA isn't GDPR compliant at all. What I meant was that the homepageowner have to inform the end user that the page transfers data to the following companies, which data and for which purpose.

Disclaimer: This is my personal understanding and I'm not a lawyer. 


But nevermind. When I'am gonna try to build it on my own the next days I will remove the code. I was hoping this was an issue while committing. 
@WolverinDEV close this issue if you're the same opinion as @Bluscream

**Comment by WolverinDEV** [comment]
Well the Google analytics is mainly for web.teaspeak.de because this is still the main side and repro where the client is available. 
But you rememberd me that I have to anonymisize the statics and add a privacy policy :)
I'll do this within the next days

**Comment by WolverinDEV** [comment]
Rejected, Its good to track the user count :)
