### ISSUE TITLE
Teaspeak server chat into log chat

### ISSUE THREAD

**Issue by Pyton-Sparky** [TeaSpeak/TeaWeb#91]
Can you add a option in the TeaSpeak Server so that the server chat message are display in the log chat?
I propose it into the TeaSpeak server simply because it's the server admin who would be able to manage it in case of each user. Because lot of users are weak in computers usage and simply login on servers is some times already a challenge.
I would appreciate it because we are playing with clans and are using a lot the global chat message to communicate between guilds

**Comment by WolverinDEV** [comment]
![](https://img.did.science/Screenshot_11-50-38.png)
Implemented within the next releases
